#!/usr/bin/env bash
# harness-lib.sh — shared helpers for the harness scripts.
#
# Sourced by BOTH scripts/poll-and-dispatch.sh (the feature/build loop) and
# scripts/learn-tick.sh (the memory loop). These are pure functions: they read
# globals the sourcing script defines (CLAUDE_PERM_ARGS, WORKTREE_BASE), and bash
# resolves those at call time — so the only requirement is that the caller sets
# its config block before it calls a helper, not before it sources this file.
#
# Generated by /harness-init. Keep this minimal — it exists only to avoid
# duplicating run_claude (and its session-id discipline) across two scripts.

# Map a name (a feature, or the literal "learn") to its worktree path. Both loops
# create sibling worktrees off the same WORKTREE_BASE, derived from the MAIN
# worktree by the sourcing script: feature paths are '<repo>-harness-<feature>',
# the memory loop's is '<repo>-harness-learn'. (Inv 3)
worktree_for() { echo "${WORKTREE_BASE}-$1"; }

# LOCAL ADDITION (not in the canonical design-doc dispatcher): make a freshly
# created worktree runnable. A bare worktree has no gitignored files
# (node_modules, .env, generated code), so signals, the PRD runner, and /learn's
# drafted-lint check would fail for reasons unrelated to the work. If the project
# has no bootstrap script, this is a no-op.
bootstrap_worktree() {
  local wt="$1"
  if [[ -x scripts/bootstrap-worktree.sh ]]; then
    ./scripts/bootstrap-worktree.sh "$wt" || \
      echo "WARN: bootstrap-worktree.sh failed for ${wt}" >&2
  fi
}

# Wrap every claude -p call. Generates a session UUID, runs claude headless with
# --session-id so the trace at ~/.claude/projects/<encoded>/<uuid>.jsonl is
# locatable later, and appends a row to .harness/sessions-<feature>.tsv. The TSV
# is the per-feature (or per-learn-sha) audit trail the STUCK / learn-review
# signals point the human into.
run_claude() {
  local step="$1" feature="$2" attempt="$3" wt="$4"; shift 4
  local sid; sid="$(uuidgen 2>/dev/null || cat /proc/sys/kernel/random/uuid 2>/dev/null || echo "noid-$$-$RANDOM")"
  local log=".harness/sessions-${feature}.tsv"
  [[ -s "$log" ]] || printf '#timestamp\tstep\tattempt\tsession_id\texit\tduration_s\n' > "$log"
  local t0; t0="$(date +%s)"
  # No print-mode --cwd flag exists; `cd` is the only way to set the working
  # directory, and it's also what gives the skill its .claude/ command + AGENTS.md
  # / CLAUDE.md discovery inside the worktree. (Inv 3 + 6: the skill operates on
  # its own worktree, never the loop's checkout.) The build loop passes the
  # per-feature worktree; the memory loop passes the '<repo>-harness-learn' worktree.
  # The `|| exit=$?` keeps a non-zero skill exit from tripping `set -e` so the row
  # below always gets written (the STUCK / learn-review dossier needs it), and
  # `return 0` keeps a failed step from aborting the rest of the tick — the absent
  # sentinel makes the next tick re-derive and retry. (Inv 1 + 4 + 5)
  # NOTE: --session-id is the documented headless flag; if your claude version
  # doesn't support it, swap for --output-format json and parse session_id out.
  local exit=0
  ( cd "$wt" && claude -p --session-id "$sid" "${CLAUDE_PERM_ARGS[@]+"${CLAUDE_PERM_ARGS[@]}"}" "$@" ) || exit=$?
  printf '%s\t%s\t%d\t%s\t%d\t%d\n' \
    "$(date -Iseconds 2>/dev/null || date)" "$step" "$attempt" "$sid" "$exit" "$(( $(date +%s) - t0 ))" >> "$log"
  return 0
}

# Render the per-feature / per-learn-sha session table (the full claude -p build
# trail) as a Markdown table on stdout. Shared by the dispatcher's signal_stuck /
# signal_human_review and the memory loop's signal_learn_review so the session IDs
# are surfaced on the PR in every terminal state.
render_sessions_table() {
  local feature="$1"
  [[ -f ".harness/sessions-${feature}.tsv" ]] || return 0
  echo '| Time | Step | Attempt | Session ID | Exit |'
  echo '|------|------|---------|------------|------|'
  grep -v '^#' ".harness/sessions-${feature}.tsv" 2>/dev/null | tail -n 20 | \
    awk -F'\t' '{printf "| %s | `%s` | %s | `%s` | %s |\n", $1, $2, $3, $4, $5}'
}
