#!/usr/bin/env bash
# poll-and-dispatch.sh — one tick of the harness outer loop.
#
# Deterministic bash. NO LLM in the decision path. The if/elif chain in the
# advance loop IS the state machine; the artifacts on disk ARE the state.
# Every section maps to one of the harness's load-bearing invariants — when this
# script and the prose disagree, the invariants win.
#
# Generated by /harness-init. Safe to edit — see the dispatcher-explained.md
# reference for what each section does and what is safe to change.

# Serialize against concurrent ticks on this node (cron + /loop, etc.). (Inv 5)
exec {lockfd}<"$0"; flock -n $lockfd || exit 0

set -euo pipefail

SLUG="$(git config user.email | cut -d@ -f1)"
WATCH="${WATCH_PATTERN:-prd/${SLUG}/*}"
# Derive the repo name from the MAIN worktree (always listed first by
# `git worktree list`), NOT from $PWD: the dispatcher runs from the detached
# '<repo>-harness' HOST worktree, so basename "$PWD" would double the suffix to
# '<repo>-harness-harness'. Per Inv 3 each in-flight feature gets its own
# ephemeral worktree at '<repo>-harness-<feature>'; the host worktree stays put,
# detached at origin/main (re-synced each tick by scripts/harness-tick.sh).
# Overridable from .harness/env (sourced below).
MAIN_WT="$(git worktree list --porcelain | sed -n '1s/^worktree //p')"
WORKTREE_BASE="../$(basename "${MAIN_WT:-$PWD}")-harness"
MAX_WORKTREES="${MAX_WORKTREES:-1}"
PLANNING_CAP="${PLANNING_CAP:-2}"         # /spec-planning retries before STUCK
VALIDATE_CAP="${VALIDATE_CAP:-2}"         # /spec-validate retries before STUCK
IMPLEMENT_CAP="${IMPLEMENT_CAP:-3}"       # PRD-runner retries before STUCK (the plan may be wrong)
LOCAL_CHECKS_CAP="${LOCAL_CHECKS_CAP:-2}" # local-checks two-strike (auto-fix → focused LLM fix → STUCK)
FEEDBACK_CAP="${FEEDBACK_CAP:-5}"         # reviewer feedback rounds before STUCK
# Convergence signal. When the reviewer has no Important findings left,
# REVIEW.md tells it to post a PR comment containing this marker. The dispatcher
# sees the marker and hands the PR to the human for /evaluate-pr. Uniform across
# reviewers (managed or self-hosted) — both can post a comment. If the reviewer
# never emits it, the feedback loop just runs to FEEDBACK_CAP and STUCKs (a clean
# PR the human merges) — acceptable degradation, no special case. Set the marker
# to EMPTY in .harness/env when there is no reviewer (converge at PR-open instead).
REVIEW_CLEAN_MARKER="${REVIEW_CLEAN_MARKER:-HARNESS_REVIEW_CLEAN}"
mkdir -p .harness

# Headless permission posture for `claude -p`. A headless session cannot show a
# permission prompt — without a posture, tool calls are denied, the skill can't
# do its work, and the step falsely STUCKs. `auto` is classifier-gated and
# prompt-free; on repeated classifier blocks the session aborts -> non-zero exit
# -> the step's retry/STUCK machinery catches it. Override in .harness/env, e.g.
#   CLAUDE_PERM_ARGS=( --dangerously-skip-permissions )
# if the CLI is Bedrock/Vertex-backed (auto is Anthropic-API only), the installed
# claude predates --permission-mode, or you want classifier-free, zero-overhead
# runs inside the isolated worktree. Set ABOVE the source line so .harness/env
# can replace the array.
CLAUDE_PERM_ARGS=( --permission-mode auto )

# Load project-local config if present (MAX_WORKTREES, WATCH_PATTERN,
# CLAUDE_PERM_ARGS, ...).
[[ -f .harness/env ]] && source .harness/env

# Shared helpers (worktree_for, bootstrap_worktree, run_claude,
# render_sessions_table) live in harness-lib.sh — the memory loop (learn-tick.sh)
# uses the same ones, so they're factored out to avoid drift. They read the config
# globals set above (CLAUDE_PERM_ARGS) and below (WORKTREE_BASE); bash resolves
# those at call time.
source "$(dirname "${BASH_SOURCE[0]}")/harness-lib.sh"

# Invariant 2: a feature/<f> is harness-owned iff prds/<f>/prd.md is committed
# to it. Hand-pushed feature/quickfix without a PRD is ignored.
has_prd() {
  git cat-file -e "origin/feature/${1}:prds/${1}/prd.md" 2>/dev/null
}

# Convergence handoff: the reviewer reported no Important findings, so
# the PR is the human's to evaluate. Post the session trail with an invitational
# framing (NOT a failure — this is the healthy terminal state of the review loop).
# Deterministic and once (the human-review-posted-<f> marker prevents re-posting).
signal_human_review() {
  local feature="$1" branch="feature/${feature}"
  local body=".harness/human-review-body-${feature}.md"
  {
    echo "## Ready for your review"
    echo
    echo "The reviewer reports no outstanding Important findings. This PR is now"
    echo "yours to **evaluate** — run \`/evaluate-pr ${feature}\` to walk the change,"
    echo "run it locally, and build a firm understanding before you merge."
    echo
    echo "**Build sessions** (the full \`claude -p\` trail — open a trace at"
    echo "\`~/.claude/projects/<encoded>/<session-id>.jsonl\` to see what each agent"
    echo "saw and concluded; useful if you decide *not* to merge and want to find"
    echo "which context shaped a decision):"
    echo
    render_sessions_table "$feature"
  } > "$body"
  gh pr comment "$branch" --body-file "$body" 2>/dev/null || true
}

# Signal STUCK to the human via the PR. Opens a draft PR if none exists yet
# (planning/validate can STUCK before any PR is open). Body includes the step,
# the cap, the per-feature session log (failing step + upstream chain), an
# optional tail of failing output, and the diagnosis-first checklist. The PR is
# the single human-facing surface; nothing else is captured to disk for the human.
signal_stuck() {
  local feature="$1" step="$2" cap="$3" output_file="${4:-}"
  touch ".harness/stuck-${feature}"
  local branch="feature/${feature}"
  local body=".harness/stuck-body-${feature}.md"
  {
    echo "## STUCK — your turn"
    echo
    echo "**Step:** \`/${step}\` — cap reached after ${cap} attempts."
    echo
    echo "**Sessions** (failing step + upstream chain — open the trace files in"
    echo "\`~/.claude/projects/<encoded-project>/<session-id>.jsonl\` to see what"
    echo "the agent saw and concluded; for a CI/server harness, your project should"
    echo "upload these as workflow artifacts):"
    echo
    if [[ -f ".harness/sessions-${feature}.tsv" ]]; then
      render_sessions_table "$feature"
      echo
    fi
    if [[ -s "$output_file" ]]; then
      echo "**Last 30 lines of failing output:**"
      echo
      echo '```'
      tail -n 30 "$output_file"
      echo '```'
      echo
    fi
    echo "## Diagnosis-first"
    echo
    echo "Your **first** job is not the code — it is to identify which piece of"
    echo "context (\`AGENTS.md\`, an Expert shard, a spec, or the PRD) misled the"
    echo "agent or was missing. Correct it on this branch *before* the code fix;"
    echo "the merge carries both into main and \`/learn\` picks up the context fix."
    echo
    echo "- [ ] **Context defect identified:** \`<file:line>\` — \`<one-line>\`"
    echo "- [ ] Corrected the context on this branch (AGENTS.md / Expert / spec / PRD)"
    echo "- [ ] Code fixed; \`./prds/${feature}/run-prd-test.sh\` passes locally"
    echo "- [ ] Ready to merge"
  } > "$body"
  if gh pr view "$branch" >/dev/null 2>&1; then
    gh pr comment "$branch" --body-file "$body" 2>/dev/null || true
  else
    gh pr create --base main --head "$branch" --draft \
                 --title "STUCK: ${feature} (${step})" --body-file "$body" 2>/dev/null || true
  fi
}

# Has the reviewer signalled "done"? True iff any PR comment contains the marker.
# Dead simple on purpose: see the marker, converge. We don't check freshness — if
# a later push lands after the marker, it came from the human (the loop is halted
# in HUMAN_REVIEW by then), and the human handles whatever the reviewer says about
# it. Deterministic, one gh call, no LLM. Empty marker = no reviewer (handled at
# PR-open), so this returns false.
reviewer_converged() {
  local branch="$1"
  [[ -n "$REVIEW_CLEAN_MARKER" ]] || return 1
  # NB: gh's --jq is a lightweight filter, NOT full jq — it has no --arg. The
  # prior `--jq --arg m "$MARKER" '<expr>'` form made gh treat --arg/m/marker/expr
  # as stray positional args ("accepts at most 1 arg(s)"), so it errored, 2>/dev/null
  # hid it, and this ALWAYS returned false — the HUMAN_REVIEW handoff never fired and
  # every PR ground to FEEDBACK_CAP and false-STUCK. Pull the comment bodies and
  # fixed-string match the marker in the shell instead.
  gh pr view "$branch" --json comments --jq '.comments[]?.body' 2>/dev/null \
    | grep -qF "$REVIEW_CLEAN_MARKER"
}

git fetch --quiet origin

# 1. Re-attach worktrees for in-flight feature/* that lost theirs.
#    In-flight work always continues regardless of MAX_WORKTREES — the cap is on
#    NEW intake, not continuation. Order is FIFO by remote branch committerdate.
in_flight=()
for feature in $(git for-each-ref --sort=committerdate \
                   --format='%(refname:lstrip=4)' \
                   refs/remotes/origin/feature/ 2>/dev/null || true); do
  has_prd "$feature" || continue
  # Liveness gate: a MERGED/CLOSED PR means this feature is DONE. Its branch may
  # still linger on origin (we never force-delete it — a merged feature/* often
  # outlives its PR), but a done feature is NOT in-flight. Skipping it here is
  # load-bearing twice over: it stops step 3 from re-spawning a pointless
  # /address-feedback on a merged PR, AND it frees the MAX_WORKTREES slot the
  # phantom was holding so step 2 can claim a waiting PRD. Step 4 still tears down
  # the local worktree. Empty state — no PR opened yet (pre-PR pipeline phase) or a
  # transient gh failure — is fail-SAFE: treat as in-flight and keep advancing,
  # never silently abandon live work. Merged is terminal, so this never rewinds. (Inv 9)
  pr_state="$(gh pr view "feature/${feature}" --json state --jq .state 2>/dev/null || echo "")"
  [[ "$pr_state" == "MERGED" || "$pr_state" == "CLOSED" ]] && continue
  wt="$(worktree_for "$feature")"
  if [[ ! -d "$wt" ]]; then
    git worktree add "$wt" "feature/${feature}" 2>/dev/null && bootstrap_worktree "$wt" || true
  fi
  [[ -d "$wt" ]] && in_flight+=("$feature")
done

# 2. Claim new PRDs up to remaining capacity (lazy claim). PRDs over cap stay in
#    prd/<slug>/* as the visible waiting queue. WATCH uses git refspec glob
#    syntax (* matches one path component). Per-dev default: prd/${SLUG}/*.
#    Shared pool: set WATCH_PATTERN=prd/*/*.
capacity=$(( MAX_WORKTREES - ${#in_flight[@]} ))
if (( capacity > 0 )); then
  for branch in $(git for-each-ref --sort=committerdate \
                    --format='%(refname:lstrip=3)' \
                    "refs/remotes/origin/${WATCH}" 2>/dev/null || true); do
    (( capacity > 0 )) || break
    feature="${branch##*/}"
    # Atomic rename = claim. Push failure (non-fast-forward) means another node
    # claimed first; skip silently. (Inv 2 + 7)
    if git push origin "origin/${branch}:refs/heads/feature/${feature}" \
                       ":refs/heads/${branch}" 2>/dev/null; then
      wt="$(worktree_for "$feature")"
      git worktree add "$wt" "feature/${feature}" 2>/dev/null && bootstrap_worktree "$wt" || true
      in_flight+=("$feature")
      capacity=$(( capacity - 1 ))
    fi
  done
fi

# 3. Advance each active feature by exactly ONE step. (Inv 5: one transition
#    per tick per branch.)
for feature in ${in_flight[@]+"${in_flight[@]}"}; do
  wt="$(worktree_for "$feature")"
  [[ -d "$wt" ]] || continue
  branch="feature/${feature}"

  # STUCK guard: a cap-hit handed this feature to the human via the PR.
  # Don't keep poking it — wait for merge/close (cleanup pass clears the
  # sentinel and the worktree).
  [[ -f ".harness/stuck-${feature}" ]] && continue

  # HUMAN_REVIEW guard: the reviewer converged and the PR was handed
  # to the human for /evaluate-pr. Halt — no advance — until the human merges or
  # closes (cleanup clears the sentinels + worktree). The human drives from here:
  # evaluate, then merge, close, or fix locally and push. The loop never re-engages.
  # Post the session trail exactly once (guarded by the -posted marker).
  if [[ -f ".harness/human-review-${feature}" ]]; then
    if [[ ! -f ".harness/human-review-posted-${feature}" ]]; then
      signal_human_review "$feature"
      touch ".harness/human-review-posted-${feature}"
    fi
    continue
  fi

  # Invariant 3 guard: worktree HEAD must match the branch we're advancing.
  # Skip otherwise (e.g., human manually checked out a different branch).
  current=$(git -C "$wt" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
  [[ "$current" == "$branch" ]] || continue

  # Wipe: discard uncommitted state from any crashed skill. `-fd` (not `-fdx`)
  # preserves gitignored files like node_modules. (Inv 1 + 6)
  ( cd "$wt" \
    && git reset --hard HEAD --quiet \
    && git clean -fd --quiet \
    && git reset --hard "origin/$branch" --quiet )

  # State machine: walk forward by exactly one step. Sentinel files gate each
  # transition. Every step has a bounded retry; at cap, signal_stuck posts to the
  # PR (opening one as a draft if necessary) with the step, the session log, an
  # optional failing-output tail, and the diagnosis-first checklist. The stuck
  # sentinel above halts further advance until the human merges or closes.
  if   [[ ! -f "${wt}/specs/${feature}/.planning-done" ]]; then
       attempts_file=".harness/planning-attempts-${feature}"
       attempts=$(cat "${attempts_file}" 2>/dev/null || echo 0)
       if (( attempts >= PLANNING_CAP )); then
         echo "STUCK: ${feature} at /spec-planning (${PLANNING_CAP}x)." >&2
         signal_stuck "$feature" "spec-planning" "$PLANNING_CAP"
       else
         echo $((attempts + 1)) > "${attempts_file}"
         run_claude spec-planning "$feature" $((attempts + 1)) "$wt" "/spec-planning ${feature}"
       fi

  elif [[ ! -f "${wt}/specs/${feature}/.validated" ]]; then
       attempts_file=".harness/validate-attempts-${feature}"
       attempts=$(cat "${attempts_file}" 2>/dev/null || echo 0)
       if (( attempts >= VALIDATE_CAP )); then
         echo "STUCK: ${feature} at /spec-validate (${VALIDATE_CAP}x)." >&2
         signal_stuck "$feature" "spec-validate" "$VALIDATE_CAP"
       else
         echo $((attempts + 1)) > "${attempts_file}"
         run_claude spec-validate "$feature" $((attempts + 1)) "$wt" "/spec-validate ${feature}"
       fi

  elif [[ ! -f "${wt}/specs/${feature}/.prd-passed" ]]; then
       # Run the PRD runner only until it first goes green, then cache the result.
       # The runner may be an LLM-as-judge (cost + non-determinism), so re-running
       # it every tick would burn tokens and could flip 0->1 and wrongly re-kick
       # implement on an already-PR'd feature. Forward-only (Inv 9): once green, the
       # PRD gate stays satisfied; local-checks (re-run every tick), CI, the
       # PRD-aware reviewer, and the human merge cover any later regression. The
       # gate still ran and passed before merge, so this is not an Inv 8 bypass.
       if ( cd "${wt}" && "./prds/${feature}/run-prd-test.sh" ); then
         # First green — record a committed+pushed sentinel so it survives the
         # tick-start wipe and is never re-run. The dispatcher (not the skill)
         # writes it because only the dispatcher's gate observed green. `|| true`:
         # a push failure self-heals (next wipe drops the un-pushed commit -> the
         # sentinel is absent -> re-run) and must not abort the tick.
         ( cd "${wt}" \
           && touch "specs/${feature}/.prd-passed" \
           && git add "specs/${feature}/.prd-passed" \
           && git commit -m "harness: PRD runner green for ${feature}" --quiet \
           && git push --quiet ) || true
       else
         # Bounded retry: if the PRD runner keeps failing, the *plan* may be broken,
         # not just the code, and re-invoking implement forever burns compute. (Inv 8)
         attempts_file=".harness/implement-attempts-${feature}"
         attempts=$(cat "${attempts_file}" 2>/dev/null || echo 0)
         if (( attempts >= IMPLEMENT_CAP )); then
           # Capture the latest failing output for the human's diagnosis dossier.
           ( cd "${wt}" && ./prds/${feature}/run-prd-test.sh ) > ".harness/stuck-output-${feature}.log" 2>&1 || true
           echo "STUCK: ${feature} at /implement-mainspec — PRD runner ${IMPLEMENT_CAP}x." >&2
           signal_stuck "$feature" "implement-mainspec" "$IMPLEMENT_CAP" ".harness/stuck-output-${feature}.log"
         else
           echo $((attempts + 1)) > "${attempts_file}"
           run_claude implement-mainspec "$feature" $((attempts + 1)) "$wt" "/implement-mainspec ${feature}"
         fi
       fi

  elif [[ -x "${wt}/scripts/local-checks.sh" ]] \
       && ! ( cd "${wt}" && ./scripts/local-checks.sh ); then
       # Optional gate. Auto-fix first (attempt 0), focused LLM fix (attempt 1),
       # then STUCK at LOCAL_CHECKS_CAP. (Inv 8)
       attempts_file=".harness/local-check-attempts-${feature}"
       attempts=$(cat "${attempts_file}" 2>/dev/null || echo 0)
       if (( attempts >= LOCAL_CHECKS_CAP )); then
         ( cd "${wt}" && ./scripts/local-checks.sh ) > ".harness/stuck-output-${feature}.log" 2>&1 || true
         echo "STUCK: ${feature} at local-checks (${LOCAL_CHECKS_CAP}x)." >&2
         signal_stuck "$feature" "local-checks" "$LOCAL_CHECKS_CAP" ".harness/stuck-output-${feature}.log"
       elif (( attempts == 0 )); then
         ( cd "${wt}" && ./scripts/local-checks.sh fix || true )
         if ! ( cd "${wt}" && git diff --quiet ); then
           ( cd "${wt}" \
             && git commit -am "chore: auto-fix lint/format" --quiet \
             && git push --quiet )
         fi
         echo 1 > "${attempts_file}"
       else
         run_claude fix-local-checks "$feature" $((attempts + 1)) "$wt" "/fix-local-checks ${feature}"
         echo $((attempts + 1)) > "${attempts_file}"
       fi

  elif ! gh pr view "${branch}" >/dev/null 2>&1; then
       gh pr create --base main --head "${branch}" --fill
       rm -f ".harness/planning-attempts-${feature}"
       rm -f ".harness/validate-attempts-${feature}"
       rm -f ".harness/local-check-attempts-${feature}"
       rm -f ".harness/implement-attempts-${feature}"
       # No reviewer configured (empty marker) → nothing to converge on; hand
       # straight to the human for /evaluate-pr. Guard halts next tick.
       [[ -z "$REVIEW_CLEAN_MARKER" ]] && touch ".harness/human-review-${feature}"

  # CONVERGED — the reviewer posted the clean marker. Hand the PR to the human
  # for /evaluate-pr. The guard above halts the feature next tick.
  # Checked BEFORE the findings loop so a clean PR never marches to a false STUCK
  # on a sticky historical COMMENTED review.
  elif reviewer_converged "${branch}"; then
       touch ".harness/human-review-${feature}"

  # Reviewer has findings and hasn't signalled done. Address them if budget
  # remains; at FEEDBACK_CAP rounds without convergence, STUCK (covers genuine
  # non-convergence AND a reviewer that flubbed the marker — human takes over).
  elif gh pr view "${branch}" --json reviews \
         --jq '.reviews[] | select(.state=="CHANGES_REQUESTED" or .state=="COMMENTED")' \
         2>/dev/null | grep -q .; then
       rounds_file=".harness/feedback-rounds-${feature}"
       rounds=$(cat "${rounds_file}" 2>/dev/null || echo 0)
       if (( rounds >= FEEDBACK_CAP )); then
         echo "STUCK: ${feature} at PR review (${FEEDBACK_CAP} rounds)." >&2
         # No tee'd output — the failure signal is the unresolved PR comments.
         signal_stuck "$feature" "address-feedback" "$FEEDBACK_CAP"
       else
         echo $((rounds + 1)) > "${rounds_file}"
         run_claude address-feedback "$feature" $((rounds + 1)) "$wt" "/address-feedback ${feature}"
       fi
  fi
done

# 4. Cleanup pass: tear down per-feature worktree + counter files for
#    closed/merged PRs. Each finished feature is torn down independently.
for feature in $(git for-each-ref --format='%(refname:lstrip=4)' \
                   refs/remotes/origin/feature/ 2>/dev/null || true); do
  state=$(gh pr view "feature/${feature}" --json state --jq .state 2>/dev/null || echo "")
  if [[ "${state}" == "MERGED" || "${state}" == "CLOSED" ]]; then
    git worktree remove "$(worktree_for "$feature")" --force 2>/dev/null || true
    rm -f ".harness/feedback-rounds-${feature}"
    rm -f ".harness/local-check-attempts-${feature}"
    rm -f ".harness/implement-attempts-${feature}"
    rm -f ".harness/planning-attempts-${feature}"
    rm -f ".harness/validate-attempts-${feature}"
    rm -f ".harness/stuck-${feature}"
    rm -f ".harness/stuck-output-${feature}.log"
    rm -f ".harness/stuck-body-${feature}.md"
    rm -f ".harness/human-review-${feature}"
    rm -f ".harness/human-review-posted-${feature}"
    rm -f ".harness/human-review-body-${feature}.md"
    rm -f ".harness/sessions-${feature}.tsv"
  fi
done

# Post-merge memory update is NOT here. /learn runs in its own loop
# (scripts/learn-tick.sh, driven by a separate `/loop … /learn-loop`), in its own
# dedicated worktree, so a multi-minute memory rebuild never blocks — and is never
# blocked by — this feature/build loop. The two loops coordinate only through git
# (the refs/harness/last-learned watermark + ls-remote idempotency on learn/<sha>).
# See references/dispatcher-explained.md ("The memory loop").

# STUCK escalation is handled inline in step 3 by signal_stuck (which opens or
# comments on the PR with the session log + checklist). The human takes over
# from there — diagnoses the context defect first, corrects it on the branch,
# fixes the code, then merges. /learn picks up the context correction at merge.
